from youtube_transcript_api import YouTubeTranscriptApi
from youtube_transcript_api.proxies import GenericProxyConfig

video_id = "5mitUXtNL_I"  # just the ID, not full URL

# ytt_api = YouTubeTranscriptApi()
ytt_api = YouTubeTranscriptApi(
    proxy_config=GenericProxyConfig(
        http_url="http://user:pass@my-custom-proxy.org:port",
        https_url="https://user:pass@my-custom-proxy.org:port",
    )
)

fetched_transcript = ytt_api.fetch(video_id)
# fetched_transcript = ytt_api.fetch(video_id, languages=['hi'])

###
# fetching of transcript defaults to english language
# user may add arg: languages=['de', 'en'] to fetch transcript in multiple languages
# Also, By default this module always chooses manually 
# created transcripts over automatically created ones, 
# if a transcript in the requested language is available 
# both manually created and generated.
###

# list available transcripts
transcript_list = ytt_api.list(video_id)
print(transcript_list)

# is iterable
for snippet in fetched_transcript:
    print(snippet.text)

# transcript = transcript_list.find_transcript(['de', 'en'])
# print(
#     transcript.video_id,
#     transcript.language,
#     transcript.language_code,
#     # whether it has been manually created or generated by YouTube
#     transcript.is_generated,
#     # whether this transcript can be translated or not
#     transcript.is_translatable,
#     # a list of languages the transcript can be translated to
#     transcript.translation_languages,
# )

# indexable
last_snippet = fetched_transcript[-1]
print(last_snippet)

# provides a length
snippet_count = len(fetched_transcript)
print(snippet_count)

